Changed env var warning to info + updated unit test + using PyPI csv2bufr
wmo-im/synop2bufr pull request #52
Opened 2024-03-26 09:50 UTC by RoryPTB

2024-03-26 15:33 UTC, david-i-berry requested changes
Suggest minor change to log message re not set environment variable.

2024-03-26 15:33 UTC, david-i-berry commented on synop2bufr/__init__.py
> +                        var_info = f"The {var} environment variable is not set, will default to missing!"  # noqa
This needs to be updated, the ENV may be present but set to missing. In this case the user will receive the message even though they have set the ENV.

2024-03-27 09:44 UTC, RoryPTB commented on synop2bufr/__init__.py
> +                if ORIGINATING_CENTRE == 65535:
I made these changes to align with your code as requested by Maaike. I will change it back now

2024-03-27 15:13 UTC, david-i-berry approved these changes

2024-03-27 15:14 UTC, merged